server:
  port: 7634
spring:
  cloud:
    stream:
      bindings:
        reportPositions-out-0:
          destination: aircraftpositions
          binder: rabbit

  rabbitmq:
    addresses: 192.168.66.100
