spring:
  cloud:
    stream:
      bindings:
        retrieveAircraftPositions-in-0:
          destination: aircraftpositions
          group: aircraftpositions
          binder: rabbit

  rabbitmq:
    addresses: 192.168.66.100
